### ISSUE TITLE
Search in editor is not working

### ISSUE THREAD

**Issue by omerlh** [Soluto/tweek#433]
Hey, 
This morning I tried to use Tweek, it loaded, but I could not search for keys. I could manually go and select keys, and it loaded successfully. By looking in the console logs, I noticed those errors:
```
Failed to load resource: the server responded with a status of 502 ()
registerServiceWorker.js:70 Error during service worker registration: DOMException: Registration failed - permission denied
    at o.d [as _captureStackTrace] (https://tweek-editor.mysoluto.com/static/js/main.2175decb.js:1:699775)
    at o._resolveFromExecutor (https://tweek-editor.mysoluto.com/static/js/main.2175decb.js:1:735329)
    at new o (https://tweek-editor.mysoluto.com/static/js/main.2175decb.js:1:727592)
    at https://tweek-editor.mysoluto.com/static/js/main.2175decb.js:1:673803
(anonymous) @ registerServiceWorker.js:70
api/search?q=authen Failed to load resource: net::ERR_FAILED
subscribeToResult.js:42 Uncaught TypeError: Failed to fetch 
```
And I think I had network issues when I open the editor, but not sure about that. Reloading the page solved the issue.

**Comment by Yshayy** [comment]
Service worker is disabled by default, this solves the issue.
